package com.mycompany.app.pdv.views;


import com.mycompany.app.pdv.entities.Produto;

import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class JpanelConsultaProduto extends javax.swing.JPanel {

    /**
     * Creates new form JpanelConsultaProduto
     */
    public JpanelConsultaProduto() {
        initComponents();
        atualizarLista();
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            filtrarTabela(jTextField1.getText());
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            filtrarTabela(jTextField1.getText());
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            filtrarTabela(jTextField1.getText());
        }
    });
         btAdicionar.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            adicionarProdutosSelecionados();
        }
    });
        
}
      
private void filtrarTabela(String termoPesquisa) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    jTable1.setRowSorter(sorter);
    
    RowFilter<DefaultTableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + termoPesquisa);
    sorter.setRowFilter(rowFilter);
}
        
        
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,  new Boolean(false)},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Valor Unit.", "Quantidade", "Selecionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/search (4).png"))); // NOI18N
        jButton4.setText("Consultar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdicionar)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btAdicionar))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        
        adicionarProdutosSelecionados();
//        JDialog dialog = new JDialog();
//        dialog.setTitle("Opções do produto");
//
//        JPanel panel = new JpanelOpcoesProduto(1);
//        dialog.add(panel);
//
//        dialog.pack();
//        dialog.setLocationRelativeTo(null);
//        dialog.setResizable(false);
//        dialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
//
//        dialog.setVisible(true);
        
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void atualizarTabela(List<Produto> produtos) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); 
    
    for (Produto produto : produtos ) {
        Object[] row = {produto.getId(), produto.getDescricao(), produto.getValorUnitario(), produto.getQuantidade(), false};
        model.addRow(row);
    }
}
    
    private void atualizarLista() {
    List<Produto> listProdutos = new ArrayList<>();
    

    Produto produto1 = new Produto();
    
    produto1.setId(1);
    produto1.setDescricao("Pão");
    produto1.setValorUnitario(10.50);
    produto1.setQuantidade(4);
    

    Produto produto2 = new Produto();
    produto2.setId(2);
    produto2.setDescricao("Geladeira");
    produto2.setValorUnitario(15.75);
    produto2.setQuantidade(32);

    Produto produto3 = new Produto();
    produto3.setId(3);
    produto3.setDescricao("Casa");
    produto3.setValorUnitario(8.99);
    produto3.setQuantidade(10);

    listProdutos.add(produto1);
    listProdutos.add(produto2);
    listProdutos.add(produto3);

    atualizarTabela(listProdutos);
    }
    
//    private void adicionarProdutosSelecionados() {
//    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//    int rowCount = model.getRowCount();
//    
//   
//    for (int i = 0; i < rowCount; i++) {
//        boolean selecionado = (boolean) jTable1.getValueAt(i, 4); // Obtém o valor do boolean "Selecionar"
//        if (selecionado) {
//            JframeVenda frameVenda = new JframeVenda();
//            int codigo = (int) jTable1.getValueAt(i, 0); // Obtém o código do produto
//            String descricao = (String) jTable1.getValueAt(i, 1); // Obtém a descrição do produto
//            double valorUnitario = (double) jTable1.getValueAt(i, 2); // Obtém o valor unitário do produto
//            int quantidade = (int) jTable1.getValueAt(i, 3);
//            double desconto = (double) jTable1.getValueAt(i, 4); // Obtém o valor unitário do produto
//         
//            frameVenda.adicionarProdutos(1, "pao", 1.0, 6, 7.0);
//        }
//    }
//}
    
    private void adicionarProdutosSelecionados() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int rowCount = model.getRowCount();
    
   
    for (int i = 0; i < rowCount; i++) {
        boolean selecionado = (boolean) jTable1.getValueAt(i, 4); // Obtém o valor do boolean "Selecionar"
        if (selecionado) {
            int codigo = (int) jTable1.getValueAt(i, 0); // Obtém o código do produto
            String descricao = (String) jTable1.getValueAt(i, 1); // Obtém a descrição do produto
            double valorUnitario = (double) jTable1.getValueAt(i, 2); // Obtém o valor unitário do produto
            
            Produto produto = new Produto(codigo, descricao, valorUnitario);
            chamaMenuOpcoes(produto);
        }
    }
}
    
    private void chamaMenuOpcoes(Produto produto){ 
        JDialog dialog = new JDialog();
        dialog.setTitle("Opções do produto");

        JPanel panel = new JpanelOpcoesProduto(produto);
        dialog.add(panel);

        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(false);
        dialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);

        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
