
package com.mycompany.app.pdv;

import com.mycompany.app.pdv.entities.Produto;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author wallg
 */
public class JpanelConsultaProduto extends javax.swing.JPanel {

    /**
     * Creates new form JpanelConsultaProduto
     */
    public JpanelConsultaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        txtProduto = new javax.swing.JTextField();
        btAdicionarProduto = new javax.swing.JButton();
        btConsultarProduto = new javax.swing.JButton();
        btVoltarProduto = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Consultar Produto:");
        add(jLabel1);
        jLabel1.setBounds(70, 80, 250, 60);

        tabelaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Valor Unit.", "Quantidade", "Selecionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 210, 1920, 470);

        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        add(txtProduto);
        txtProduto.setBounds(280, 80, 827, 70);

        btAdicionarProduto.setBackground(new java.awt.Color(51, 255, 0));
        btAdicionarProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAdicionarProduto.setForeground(new java.awt.Color(0, 0, 0));
        btAdicionarProduto.setText("Adicionar");
        btAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarProdutoActionPerformed(evt);
            }
        });
        add(btAdicionarProduto);
        btAdicionarProduto.setBounds(1710, 700, 190, 70);

        btConsultarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btConsultarProduto.setText("CONSULTAR");
        btConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarProdutoActionPerformed(evt);
            }
        });
        add(btConsultarProduto);
        btConsultarProduto.setBounds(1130, 80, 217, 70);

        btVoltarProduto.setBackground(new java.awt.Color(255, 153, 51));
        btVoltarProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btVoltarProduto.setForeground(new java.awt.Color(0, 0, 0));
        btVoltarProduto.setText("Voltar");
        add(btVoltarProduto);
        btVoltarProduto.setBounds(1480, 700, 190, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdicionarProdutoActionPerformed

    private void btConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarProdutoActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarProduto;
    private javax.swing.JButton btConsultarProduto;
    private javax.swing.JButton btVoltarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}
